name: ehon_frontend
description: A picture book generation app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0
  lottie: ^3.1.0
  supabase_flutter: ^2.0.0  # ⭐ 追加
  uuid: ^4.5.1  # ⭐ 追加
  shared_preferences: ^2.2.0  # ⭐ 追加
  url_launcher: ^6.2.1
  in_app_purchase: ^3.1.11  # iOS課金機能
  in_app_purchase_storekit: ^0.3.6+1  # iOS StoreKit


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/Images/
    - assets/animations/
    - assets/animations/Paint Brush.json
    - assets/animations/BOOK WALKING.json
    - assets/animations/Book.json
    - assets/Images/watercolor_sample.jpeg
